# Generated by Django 4.2.13 on 2024-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
