# Generated by Django 4.2.13 on 2024-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0003_testingaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vanribality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vanribality', models.CharField(max_length=100)),
                ('Risk', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=10000)),
                ('Impace', models.CharField(max_length=10000)),
                ('Recommendation', models.CharField(max_length=10000)),
            ],
        ),
    ]
